# Coolify Deployment Configuration
# https://coolify.io/docs

version: '1.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001"
    volumes:
      - meeting_data:/app/data
      - meeting_notes:/app/meeting-notes
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5001/', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  meeting_data:
  meeting_notes:
